# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StudexCli < Formula
  desc "A command line interface for Studex Portal"
  homepage "https://github.com/itshivams/Studex-CLI"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.0/studex-cli_Darwin_x86_64.tar.gz"
      sha256 "fb41ba84b145a736779dd17b11c3483f3dcf0da98ccfe1b14625d9e1ff05d25a"

      def install
        bin.install "studex-cli"
      end
    end
    on_arm do
      url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.0/studex-cli_Darwin_arm64.tar.gz"
      sha256 "5029f3d00d56f80f0c3dcdec7bcc13fa92a3904e500fd9065198edd6ae92d79d"

      def install
        bin.install "studex-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.0/studex-cli_Linux_x86_64.tar.gz"
        sha256 "d4b3fadecb860ad11916ba15a4f17f886d23ca93ead216856865c72f6f435124"

        def install
          bin.install "studex-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.0/studex-cli_Linux_arm64.tar.gz"
        sha256 "96cfa493544066688dd47ef630c6f699fb1e567694741e835225d3c5221248cd"

        def install
          bin.install "studex-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/studex-cli", "--version"
  end
end
