# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StudexCli < Formula
  desc "A command line interface for Studex Portal"
  homepage "https://github.com/itshivams/Studex-CLI"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.0/studex-cli_Darwin_x86_64.tar.gz"
      sha256 "e1c440970584f3d5e1b307d73b083a01a22782b7f81426aeb0e4aa23e4618671"

      def install
        bin.install "studex-cli"
      end
    end
    on_arm do
      url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.0/studex-cli_Darwin_arm64.tar.gz"
      sha256 "22ad0498bc4957e3966a180b385024be23ccb14778ed547effe8e431ef3030f2"

      def install
        bin.install "studex-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.0/studex-cli_Linux_x86_64.tar.gz"
        sha256 "3859b297038631dac2c41dc5f54b8dff853957e1f08a2c057b2e21dcaa06c8f8"

        def install
          bin.install "studex-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.0/studex-cli_Linux_arm64.tar.gz"
        sha256 "494b3c63edf27a367eec98ce7d0d472abbd3ce2d2489d396ecf2458a3a6ea585"

        def install
          bin.install "studex-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/studex-cli", "--version"
  end
end
