# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StudexCli < Formula
  desc "A command line interface for Studex Portal"
  homepage "https://github.com/itshivams/Studex-CLI"
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.2/studex-cli_Darwin_x86_64.tar.gz"
      sha256 "5113bea43473cfa856b44ed186b435306ad83fa976abbd61cdf450d39f324f85"

      def install
        bin.install "studex-cli"
      end
    end
    on_arm do
      url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.2/studex-cli_Darwin_arm64.tar.gz"
      sha256 "6b6b03a63faa01fb215e31dd65dc2a3a09b0d43e254889082d49a7348204abc3"

      def install
        bin.install "studex-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.2/studex-cli_Linux_x86_64.tar.gz"
        sha256 "dd4382ac198a47a84bee26edc5937aaf68cbf668b45b4f970cf8fe524360266d"

        def install
          bin.install "studex-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/itshivams/Studex-CLI/releases/download/v1.0.2/studex-cli_Linux_arm64.tar.gz"
        sha256 "878cf4b288fed9ccbe6912d2e03dfdf9eb4eac4224ff02a3c80beb31dc53345c"

        def install
          bin.install "studex-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/studex-cli", "--version"
  end
end
